import { useMemo, useState } from "react";
import { Brain, Bot, ShieldCheck, Power, Search, Globe2, Palette, History, Target, Activity, Database, Send, Sparkles, Package, ShoppingBag, Users, Euro, AlertTriangle, CheckCircle2, FlaskConical } from "lucide-react";
import { backendStorage } from "../../lib/backendStorage";
import { toast } from "sonner";

type Mode="AUTO"|"ASK"|"BLOCK";
const initialPermissions:Record<string,Mode>={internet_research:"AUTO",learn_from_orders:"AUTO",analyze_sales:"AUTO",answer_basic_questions:"AUTO",modify_stock:"ASK",change_prices:"ASK",refunds:"BLOCK",payments:"BLOCK",publish_web_changes:"ASK",create_products:"ASK",send_whatsapp:"ASK",send_email:"ASK"};
const labels:Record<string,string>={internet_research:"Investigar en Internet",learn_from_orders:"Aprender de pedidos",analyze_sales:"Analizar ventas",answer_basic_questions:"Responder preguntas básicas",modify_stock:"Modificar stock",change_prices:"Cambiar precios",refunds:"Hacer devoluciones",payments:"Realizar pagos",publish_web_changes:"Publicar cambios web",create_products:"Crear productos",send_whatsapp:"Enviar WhatsApp",send_email:"Enviar emails"};

export function AdminHerenciaNeural(){
 const [tab,setTab]=useState("command");
 const [autonomy,setAutonomy]=useState(()=>backendStorage.getItem("neuralAutonomy")!=="stopped");
 const [permissions,setPermissions]=useState<Record<string,Mode>>(()=>{try{return {...initialPermissions,...JSON.parse(backendStorage.getItem("neuralPermissions")||"{}")}}catch{return initialPermissions}});
 const [message,setMessage]=useState("");
 const [messages,setMessages]=useState([{role:"neural",text:"Hola Daniel. Soy HERENCIA Neural. Puedo analizar el negocio, investigar, aprender y preparar acciones dentro de los permisos que me concedas."}]);
 const [goals,setGoals]=useState([{name:"Aumentar ventas de jardinería",progress:65},{name:"Mejorar conversión web",progress:40}]);
 const [goal,setGoal]=useState("");
 const stats=useMemo(()=>({agents:12,tasks:4,approvals:Object.values(permissions).filter(v=>v==="ASK").length}),[permissions]);
 const persistPerms=(next:Record<string,Mode>)=>{setPermissions(next);void backendStorage.setItem("neuralPermissions",JSON.stringify(next));};
 const cycle=(key:string)=>{const order:Mode[]=["AUTO","ASK","BLOCK"];const next={...permissions,[key]:order[(order.indexOf(permissions[key])+1)%3]};persistPerms(next);toast.success(`${labels[key]}: ${next[key]}`);};
 const stop=()=>{const next=!autonomy;setAutonomy(next);void backendStorage.setItem("neuralAutonomy",next?"active":"stopped");toast[next?"success":"warning"](next?"Autonomía reactivada":"Autonomía detenida");};
 const send=()=>{if(!message.trim())return;const q=message.trim();setMessages(m=>[...m,{role:"user",text:q},{role:"neural",text:"He recibido la orden. La registraré como tarea y antes de ejecutar cualquier acción comprobaré el Permission Kernel. Las acciones sensibles requerirán tu autorización."}]);setMessage("");};
 const addGoal=()=>{if(!goal.trim())return;setGoals(g=>[...g,{name:goal.trim(),progress:0}]);setGoal("");toast.success("Objetivo añadido");};
 const tabs=[["command","Command Center",Brain],["agents","Células / Agentes",Bot],["memory","Memoria",Database],["research","Investigación",Globe2],["designer","Neural Designer",Palette],["goals","Objetivos",Target],["permissions","Permisos",ShieldCheck],["activity","Actividad",Activity],["lab","Neural Lab",FlaskConical],["history","Time Machine",History]] as const;
 return <div className="space-y-6">
  <div className="rounded-3xl border bg-gradient-to-r from-emerald-950 to-emerald-800 text-white p-6 shadow-xl">
   <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-5"><div className="flex gap-4 items-center"><div className="p-3 bg-white/10 rounded-2xl"><Brain className="w-9 h-9"/></div><div><h1 className="text-3xl font-black">HERENCIA Neural</h1><p className="text-emerald-100">Tu socio digital para hacer crecer Herencia</p></div></div>
   <div className="flex flex-wrap gap-3 items-center"><Badge text={autonomy?"Neural activa":"Autonomía detenida"} ok={autonomy}/><span className="px-4 py-2 rounded-xl bg-white/10">{stats.agents} agentes</span><span className="px-4 py-2 rounded-xl bg-white/10">{stats.tasks} tareas</span><button onClick={stop} className={`px-5 py-3 rounded-xl font-bold flex gap-2 items-center ${autonomy?"bg-red-500 hover:bg-red-600":"bg-emerald-500 hover:bg-emerald-600"}`}><Power className="w-5 h-5"/>{autonomy?"DETENER AUTONOMÍA":"REACTIVAR"}</button></div></div>
  </div>
  <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap px-4 py-2.5 rounded-xl border flex items-center gap-2 font-semibold ${tab===id?"bg-primary text-primary-foreground border-primary":"bg-card hover:bg-muted"}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>
  {tab==="command"&&<div className="grid xl:grid-cols-3 gap-5">
   <Panel title="Chat con HERENCIA" icon={Sparkles} className="xl:col-span-2"><div className="h-72 overflow-y-auto space-y-3 pr-2">{messages.map((m,i)=><div key={i} className={`max-w-[85%] rounded-2xl p-4 ${m.role==="user"?"ml-auto bg-primary text-primary-foreground":"bg-muted"}`}>{m.text}</div>)}</div><div className="flex gap-2 mt-4"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} className="flex-1 border bg-background rounded-xl px-4" placeholder="Dile a Neural qué quieres hacer…"/><button onClick={send} className="p-3 rounded-xl bg-primary text-primary-foreground"><Send/></button></div></Panel>
   <Panel title="Estado Neural" icon={Activity}><Metric icon={ShoppingBag} label="Pedidos hoy" value="Datos en vivo"/><Metric icon={Euro} label="Ventas" value="Conectado al ERP"/><Metric icon={Users} label="Clientes" value="CRM disponible"/><Metric icon={Package} label="Inventario" value="Monitorizable"/><div className="mt-4 p-3 rounded-xl bg-amber-50 text-amber-900 flex gap-2"><AlertTriangle className="w-5 h-5 shrink-0"/>Las acciones ASK esperan tu aprobación.</div></Panel>
   <Panel title="Células / Agentes" icon={Bot} className="xl:col-span-2"><div className="grid sm:grid-cols-3 lg:grid-cols-4 gap-3">{["Núcleo","Clientes","Ventas","Inventario","Diseño Web","Investigación","Memoria","Planificación","Reflexión","Finanzas","Proveedores","Analítica"].map(x=><button onClick={()=>toast.info(`Agente ${x}: listo para inspección`)} key={x} className="p-4 border rounded-2xl hover:border-primary hover:bg-primary/5 text-left"><div className="w-9 h-9 rounded-full bg-emerald-100 flex items-center justify-center mb-2"><Bot className="w-5 h-5 text-emerald-800"/></div><b>{x}</b><p className="text-xs text-muted-foreground mt-1">Activo · supervisado</p></button>)}</div></Panel>
   <Panel title="Aprobaciones" icon={ShieldCheck}><p className="text-sm text-muted-foreground mb-3">{stats.approvals} capacidades requieren consulta.</p><button onClick={()=>setTab("permissions")} className="w-full py-3 rounded-xl bg-primary text-primary-foreground font-bold">Revisar permisos</button></Panel>
  </div>}
  {tab==="permissions"&&<Panel title="Permission Kernel" icon={ShieldCheck}><p className="text-muted-foreground mb-4">Pulsa cada permiso para cambiar entre Autónomo → Consultar → Bloqueado. Neural no puede modificar esta capa por sí misma.</p><div className="grid md:grid-cols-2 gap-3">{Object.entries(permissions).map(([k,v])=><button key={k} onClick={()=>cycle(k)} className="flex justify-between items-center border rounded-xl p-4 hover:bg-muted"><span className="font-medium">{labels[k]||k}</span><ModeBadge mode={v}/></button>)}</div></Panel>}
  {tab==="goals"&&<Panel title="Objetivos de Neural" icon={Target}><div className="flex gap-2 mb-5"><input value={goal} onChange={e=>setGoal(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addGoal()} className="flex-1 border rounded-xl px-4 bg-background" placeholder="Ej. aumentar ventas de jardinería"/><button onClick={addGoal} className="px-5 py-3 rounded-xl bg-primary text-primary-foreground font-bold">Añadir</button></div><div className="space-y-4">{goals.map((g,i)=><div key={i} className="border rounded-2xl p-4"><div className="flex justify-between"><b>{g.name}</b><span>{g.progress}%</span></div><div className="h-2 bg-muted rounded-full mt-3 overflow-hidden"><div className="h-full bg-primary" style={{width:`${g.progress}%`}}/></div></div>)}</div></Panel>}
  {tab==="agents"&&<Generic title="Células / Agentes" icon={Bot} text="Red de agentes especializados. Cada agente opera con herramientas tipadas, memoria relevante y los mismos límites del Permission Kernel."/>}
  {tab==="memory"&&<Generic title="Memoria" icon={Database} text="Memoria de trabajo, experiencias, conocimiento verificado, reglas de Herencia, correcciones y preferencias. Las conversaciones no se convierten automáticamente en hechos."/>}
  {tab==="research"&&<Generic title="Investigación en Internet" icon={Search} text="Centro de investigación con procedencia, fecha, confianza y verificación antes de promover información a conocimiento de Herencia."/>}
  {tab==="designer"&&<Generic title="Neural Designer" icon={Palette} text="Crea y modifica secciones, botones, imágenes, textos, tipografía, grids y responsive mediante planes estructurados, vista previa, aprobación, publicación y rollback."/>}
  {tab==="activity"&&<Generic title="Actividad y auditoría" icon={Activity} text="Registro de acciones, intención, herramienta, permiso evaluado, resultado y autorización. La auditoría no puede ser borrada por Neural."/>}
  {tab==="lab"&&<Generic title="Neural Lab" icon={FlaskConical} text="Laboratorio aislado para variantes de agentes, mutaciones, evaluación y selección. Ninguna variante obtiene permisos nuevos ni pasa sola a producción."/>}
  {tab==="history"&&<Generic title="Time Machine" icon={History} text="Historial de versiones para comparar cambios del sitio, restaurar versiones y proteger producción."/>}
 </div>;
}
function Panel({title,icon:Icon,children,className=""}:any){return <section className={`bg-card border rounded-3xl p-5 shadow-sm ${className}`}><h2 className="font-black text-lg flex items-center gap-2 mb-4"><Icon className="w-5 h-5 text-primary"/>{title}</h2>{children}</section>}
function Generic({title,icon,text}:any){return <Panel title={title} icon={icon}><div className="min-h-64 flex items-center justify-center"><div className="max-w-2xl text-center"><p className="text-lg text-muted-foreground">{text}</p><div className="mt-6 inline-flex gap-2 items-center text-emerald-700 bg-emerald-50 px-4 py-2 rounded-xl"><CheckCircle2 className="w-5 h-5"/>Módulo preparado para conexión progresiva con datos reales</div></div></div></Panel>}
function Badge({text,ok}:any){return <span className={`px-4 py-2 rounded-xl font-bold ${ok?"bg-emerald-400/20 text-emerald-50":"bg-red-400/20 text-red-50"}`}>{text}</span>}
function ModeBadge({mode}:{mode:Mode}){return <span className={`px-3 py-1 rounded-full text-xs font-black ${mode==="AUTO"?"bg-emerald-100 text-emerald-800":mode==="ASK"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-800"}`}>{mode==="AUTO"?"AUTÓNOMO":mode==="ASK"?"CONSULTAR":"BLOQUEADO"}</span>}
function Metric({icon:Icon,label,value}:any){return <div className="flex gap-3 items-center py-3 border-b last:border-0"><div className="p-2 bg-primary/10 rounded-xl"><Icon className="w-5 h-5 text-primary"/></div><div><p className="text-xs text-muted-foreground">{label}</p><b>{value}</b></div></div>}
