import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, PackageCheck, TrendingDown } from "lucide-react";
import { backendStorage } from "../../lib/backendStorage";

export function AdminStockControl(){
  const [products,setProducts]=useState<any[]>([]);
  const [threshold,setThreshold]=useState(3);
  useEffect(()=>{const load=()=>{try{setProducts(JSON.parse(backendStorage.getItem("adminProducts")||"[]"));const suite=JSON.parse(backendStorage.getItem("businessSuiteSettings")||"{}");setThreshold(Math.max(0,Number(suite.lowStockThreshold??3)));}catch{setProducts([]);}};load();window.addEventListener("backend-storage",load);return()=>window.removeEventListener("backend-storage",load);},[]);
  const metrics=useMemo(()=>{const active=products.filter(p=>p.active!==false);const low=active.filter(p=>Number(p.stock||0)<=threshold);const none=active.filter(p=>Number(p.stock||0)<=0);const value=active.reduce((s,p)=>s+Number(p.stock||0)*Number(p.price||0),0);return{active,low,none,value};},[products,threshold]);
  return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card icon={Boxes} label="Productos" value={String(metrics.active.length)}/><Card icon={AlertTriangle} label={`Stock ≤ ${threshold}`} value={String(metrics.low.length)}/><Card icon={TrendingDown} label="Agotados" value={String(metrics.none.length)}/><Card icon={PackageCheck} label="Valor inventario" value={new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(metrics.value)}/></div>
  <section className="rounded-2xl border border-border bg-card p-6"><h2 className="text-2xl font-black">Alertas de stock</h2><p className="text-sm text-muted-foreground">Lee directamente el catálogo real de Herencia.</p><div className="mt-5 space-y-2">{metrics.low.length===0?<p className="text-sm text-muted-foreground">Sin alertas.</p>:metrics.low.map((p:any)=><div key={p.id} className="flex items-center justify-between rounded-xl border border-border p-4"><div><p className="font-semibold">{p.name}</p><p className="text-xs text-muted-foreground">SKU: {p.sku||p.id}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${Number(p.stock||0)<=0?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{Number(p.stock||0)} uds.</span></div>)}</div></section></div>;
}
function Card({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-2xl border border-border bg-card p-5"><Icon className="h-6 w-6 text-primary"/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
