import { useState } from "react";
import { CheckCircle2, AlertTriangle, RefreshCw, Server, CreditCard, Brain, ShoppingBag } from "lucide-react";
import { backendApi } from "../../lib/backendStorage";
type Check={name:string;ok:boolean;detail:string};
export function AdminSystemAudit(){
 const [running,setRunning]=useState(false),[checks,setChecks]=useState<Check[]>([]),[ranAt,setRanAt]=useState("");
 const run=async()=>{setRunning(true);const out:Check[]=[];
  try{const h=await backendApi.health();out.push({name:"Backend / Railway",ok:!!h.ok,detail:h.ok?"API responde correctamente":"API sin respuesta válida"});}catch(e:any){out.push({name:"Backend / Railway",ok:false,detail:e?.message||"Sin conexión"});}
  try{const p=await backendApi.posSelfTest();out.push(...(p.tests||[]).map((t:any)=>({name:"TPV · "+t.name,ok:!!t.ok,detail:t.detail})));out.push({name:"Stripe / tarjeta",ok:!!p.cardReady,detail:p.cardReady?"Configuración disponible":"Falta configuración o validación"});out.push({name:"Datos fiscales",ok:!!p.fiscalReady,detail:p.fiscalReady?"Datos del emisor configurados":"Completa los datos fiscales del emisor"});}catch(e:any){out.push({name:"TPV",ok:false,detail:e?.message||"No se pudo ejecutar el autotest"});}
  try{const n=await backendApi.neuralSelfTest();out.push({name:"HERENCIA Neural",ok:n?.ok!==false,detail:n?.ok===false?(n?.error||"Autotest con incidencias"):"Core Neural responde"});}catch(e:any){out.push({name:"HERENCIA Neural",ok:false,detail:e?.message||"Sin respuesta"});}
  try{const o=await backendApi.listOrders();out.push({name:"Pedidos / Supabase",ok:Array.isArray(o.orders),detail:Array.isArray(o.orders)?o.orders.length+" pedidos accesibles":"Respuesta inválida"});}catch(e:any){out.push({name:"Pedidos / Supabase",ok:false,detail:e?.message||"No accesible"});}
  setChecks(out);setRanAt(new Date().toLocaleString("es-ES"));setRunning(false);
 };
 const ok=checks.filter(c=>c.ok).length;
 return <div className="space-y-6"><section className="rounded-[2rem] border bg-white p-6 shadow-xl"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-black">Diagnóstico de producción</h1><p className="mt-2 text-zinc-500">Comprueba servicios reales sin crear pedidos ni efectuar cobros.</p></div><button onClick={run} disabled={running} className="rounded-2xl bg-zinc-950 px-5 py-3 font-black text-white disabled:opacity-50"><RefreshCw className={"mr-2 inline h-4 w-4 "+(running?"animate-spin":"")}/>Ejecutar diagnóstico</button></div>{checks.length>0&&<div className="mt-5 rounded-2xl bg-zinc-50 p-4 font-bold">{ok}/{checks.length} comprobaciones correctas · {ranAt}</div>}</section><div className="grid gap-4 md:grid-cols-2">{checks.map((c,i)=><div key={i} className={"rounded-3xl border p-5 "+(c.ok?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50")}><div className="flex gap-3">{c.ok?<CheckCircle2 className="text-emerald-600"/>:<AlertTriangle className="text-amber-600"/>}<div><h3 className="font-black">{c.name}</h3><p className="mt-1 text-sm text-zinc-600">{c.detail}</p></div></div></div>)}</div>{!checks.length&&<div className="rounded-3xl border border-dashed p-10 text-center text-zinc-500"><Server className="mx-auto mb-3"/><p>Ejecuta el diagnóstico para comprobar backend, TPV, pagos, pedidos y Neural.</p><div className="mt-4 flex justify-center gap-4 text-zinc-400"><CreditCard/><ShoppingBag/><Brain/></div></div>}</div>;
}